const DEFAULT_CONFIG = {
  grid: "4x8", show_date: false, date_text: "", label_text: "",
  username_font_size: 14, password_font_size: 12, date_font_size: 10, label_font_size: 12,
  username_x: 50, username_y: 40, password_x: 50, password_y: 60,
  date_x: 50, date_y: 85, label_x: 50, label_y: 10,
  username_color: "#000000", password_color: "#000000",
  date_color: "#000000", label_color: "#000000",
  show_counter: true,
  show_qr: false, qr_x: 50, qr_y: 75, qr_size: 25,
  qr_content: "username",
  custom_font: null,
  // QR Style
  qr_fg_color: "#000000",
  qr_bg_color: "#ffffff",
  qr_dot_style: "square",
  qr_eye_color: "",
  qr_use_gradient: false,
  qr_gradient_color1: "#000000",
  qr_gradient_color2: "#0066ff",
  qr_gradient_type: "linear",
  qr_logo: null,
  qr_logo_size: 20,
  qr_fg_image: null,
  qr_frame: false,
  qr_frame_color: "#000000",
  qr_frame_width: 2,
  qr_bg_shape: "none",
};
